server:
  host: localhost
  port: 5000
  debug: true
  cors_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000

ollama:
  base_url: http://localhost:11434
  model: qwen2.5:latest
  temperature: 0.7
  max_tokens: 1000
  timeout: 30

storage:
  type: memory
  cleanup_interval: 3600  # seconds
  max_cart_items: 50
  max_conversation_age: 86400  # 24 hours in seconds

api:
  version: v1
  prefix: /api/v1
  rate_limit: 100  # requests per minute
  timeout: 30  # seconds

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"

security:
  jwt_secret: "your-secret-key-here"  # Change in production
  jwt_algorithm: "HS256"
  jwt_expiry: 3600  # 1 hour in seconds
  password_salt: "your-salt-here"  # Change in production 